# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ml_service_rpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ml_service_rpc.proto',
  package='ml_service_rpc',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14ml_service_rpc.proto\x12\x0eml_service_rpc\"\x1e\n\tDataProto\x12\x11\n\tdata_json\x18\x01 \x01(\t\"\x1f\n\nModelProto\x12\x11\n\tdata_json\x18\x01 \x01(\t2P\n\ngrpcServer\x12\x42\n\x07process\x12\x19.ml_service_rpc.DataProto\x1a\x1a.ml_service_rpc.ModelProto\"\x00\x62\x06proto3'
)




_DATAPROTO = _descriptor.Descriptor(
  name='DataProto',
  full_name='ml_service_rpc.DataProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data_json', full_name='ml_service_rpc.DataProto.data_json', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=70,
)


_MODELPROTO = _descriptor.Descriptor(
  name='ModelProto',
  full_name='ml_service_rpc.ModelProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data_json', full_name='ml_service_rpc.ModelProto.data_json', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=103,
)

DESCRIPTOR.message_types_by_name['DataProto'] = _DATAPROTO
DESCRIPTOR.message_types_by_name['ModelProto'] = _MODELPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataProto = _reflection.GeneratedProtocolMessageType('DataProto', (_message.Message,), {
  'DESCRIPTOR' : _DATAPROTO,
  '__module__' : 'ml_service_rpc_pb2'
  # @@protoc_insertion_point(class_scope:ml_service_rpc.DataProto)
  })
_sym_db.RegisterMessage(DataProto)

ModelProto = _reflection.GeneratedProtocolMessageType('ModelProto', (_message.Message,), {
  'DESCRIPTOR' : _MODELPROTO,
  '__module__' : 'ml_service_rpc_pb2'
  # @@protoc_insertion_point(class_scope:ml_service_rpc.ModelProto)
  })
_sym_db.RegisterMessage(ModelProto)



_GRPCSERVER = _descriptor.ServiceDescriptor(
  name='grpcServer',
  full_name='ml_service_rpc.grpcServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=105,
  serialized_end=185,
  methods=[
  _descriptor.MethodDescriptor(
    name='process',
    full_name='ml_service_rpc.grpcServer.process',
    index=0,
    containing_service=None,
    input_type=_DATAPROTO,
    output_type=_MODELPROTO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GRPCSERVER)

DESCRIPTOR.services_by_name['grpcServer'] = _GRPCSERVER

# @@protoc_insertion_point(module_scope)
